spring:
  data:
    mongodb:
      host: localhost
      database: myDatabase
      auto-index-creation: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: tiger
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

logging:
  level:
    com:
      gyarsilalsolanki011:
        JournalApp: DEBUG

weather:
  api:
    key: d4b565e178d6c7d57dca471270563602
