spring:
  data:
    mongodb:
      host: localhost
      database: myDatabase
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8080

logging:
  level:
    com:
      gyarsilalsolanki011:
        JournalApp: DEBUG

weather:
  api:
    key: d4b565e178d6c7d57dca471270563602
